version: '3.9'

services:
  mysql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MySQL_Server
    restart: always
    volumes:
      - "./mssql:/var/opt/mssql/data"
    environment:
      TZ: Europe/Berlin
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWD}"
    ports:
      - "1433:1433"
